task:
  matrix:
  - name: Android App Build
    windows_container:
      image: cirrusci/windowsservercore:2019
    environment:
      - GITHUB_TOKEN: ENCRYPTED[38a5a4b83d9859dccc98655bdc993fb9da11ad43d0c787473b692f45732505f167335e45564474e9f3a1cbe7a883b3ae]
    env:
        CIRRUS_SHELL: powershell    
    setup_script:
    - $env:package_version = (Invoke-WebRequest  -UseBasicParsing -Uri "https://api.github.com/repos/JukaLang/juka/releases/latest" | ConvertFrom-Json).tag_name
    - choco feature enable -n=allowGlobalConfirmation
    - choco install -y --no-progress flutter
    - choco install -y -f -r --no-progress --acceptlicense android-sdk
    - refreshenv
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - SET AndroidSdkDirectory=C:\Android\android-sdk
    - cd C:\Android\android-sdk
    - flutter config --android-sdk C:\Android\android-sdk
    - flutter doctor --android-licenses --android-sdk C:\Android\android-sdk
    - Invoke-WebRequest -OutFile temp.zip -Uri https://download.visualstudio.microsoft.com/download/pr/7c4e5883-6139-4093-a1cf-5f0c6fabce89/60a342b67d120328c41fe6c7ff13890b/dotnet-sdk-7.0.100-preview.6.22352.1-win-x64.zip
    - Expand-Archive -Path temp.zip -DestinationPath ./
    script:
    - SET AndroidSdkDirectory=C:\Android\android-sdk
    - ./dotnet workload restore
    - ./dotnet publish -f net6.0-android -c Release -o output /p:AndroidSdkDirectory=C:\Android\android-sdk
    - Get-Location
    package_script:
    - Move-Item -Path C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\output\com.companyname.jukaapp-Signed.apk -Destination C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\output\Juka_${env:package_version}.apk
    upload_script: |
        #!/usr/bin/env bash

        if [[ "$CIRRUS_RELEASE" == "" ]]; then
            echo "Not a release. No need to deploy!"
            exit 0
        fi

        if [[ "$GITHUB_TOKEN" == "" ]]; then
            echo "Please provide GitHub access token via GITHUB_TOKEN environment variable!"
            exit 1
        fi

        file_content_type="application/octet-stream"

        files_to_upload=(
            "/tmp/cirrus-ci-build/bin/Release/net6.0-android/publish/Juka_${env:package_version}.apk"
        )

        for fpath in "${files_to_upload[@]}"
        do
            echo "Uploading $fpath..."
            name=$(basename "$fpath")
            url_to_upload="https://uploads.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/$CIRRUS_RELEASE/assets?name=$name"
            curl -X POST \
            --data-binary @$fpath \
            --header "Authorization: token $GITHUB_TOKEN" \
            --header "Content-Type: $file_content_type" \
            $url_to_upload
        done