task:
  matrix:
  - name: Linux Build
    container:
      image: ubuntu:latest
    environment:
      - GITHUB_TOKEN: ENCRYPTED[38a5a4b83d9859dccc98655bdc993fb9da11ad43d0c787473b692f45732505f167335e45564474e9f3a1cbe7a883b3ae]
    setup_script:
    - mkdir /dotnet
    - apt-get update
    - apt-get install -y wget curl jq libncurses5 libicu-dev libssl-dev
    - export JUKTEMP=$(curl "https://api.github.com/repos/JukaLang/juka/releases/latest" | jq -r ".tag_name")
    - wget -q https://download.visualstudio.microsoft.com/download/pr/9762c43b-6de2-44aa-928d-61bec028a330/ba4d124e5384ae5c5a4599afbc41b1bf/dotnet-sdk-7.0.100-preview.6.22352.1-linux-x64.tar.gz
    - tar xf dotnet-sdk-7.0.100-preview.6.22352.1-linux-x64.tar.gz -C /dotnet/
    script:
    - /dotnet/dotnet workload install android
    - /dotnet/dotnet publish -f net6.0-android -c Release
    package_script:
    - mv /tmp/cirrus-ci-build/bin/Release/net6.0-android/publish/com.companyname.jukaapp-Signed.apk /tmp/cirrus-ci-build/bin/Release/net6.0-android/publish/Juka_${JUKTEMP}.apk
    upload_script: |
        #!/usr/bin/env bash

        if [[ "$CIRRUS_RELEASE" == "" ]]; then
            echo "Not a release. No need to deploy!"
            exit 0
        fi

        if [[ "$GITHUB_TOKEN" == "" ]]; then
            echo "Please provide GitHub access token via GITHUB_TOKEN environment variable!"
            exit 1
        fi

        file_content_type="application/octet-stream"

        files_to_upload=(
            "/tmp/cirrus-ci-build/bin/Release/net6.0-android/publish/Juka_${JUKTEMP}.apk"
        )

        for fpath in "${files_to_upload[@]}"
        do
            echo "Uploading $fpath..."
            name=$(basename "$fpath")
            url_to_upload="https://uploads.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/$CIRRUS_RELEASE/assets?name=$name"
            curl -X POST \
            --data-binary @$fpath \
            --header "Authorization: token $GITHUB_TOKEN" \
            --header "Content-Type: $file_content_type" \
            $url_to_upload
        done