task:
  matrix:
  - name: Android App Build
    windows_container:
      image: cirrusci/windowsservercore:2019
    environment:
      - GITHUB_TOKEN: ENCRYPTED[38a5a4b83d9859dccc98655bdc993fb9da11ad43d0c787473b692f45732505f167335e45564474e9f3a1cbe7a883b3ae]
    env:
        CIRRUS_SHELL: powershell    
    setup_script:
    - choco install --no-progress -y android-sdk dotnet-sdk --pre 
    - refreshenv
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - dotnet workload install android 
    - refreshenv
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    script:
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - dotnet workload restore
    compile_script:
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
    - dotnet publish -f net6.0-android -c Release -o output
    - Get-Location
    package_script:
    - $env:package_version = (Invoke-WebRequest  -UseBasicParsing -Uri "https://api.github.com/repos/JukaLang/juka/releases/latest" | ConvertFrom-Json).tag_name
    - Move-Item -Path C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\output\com.companyname.jukaapp-Signed.apk -Destination C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\output\Juka_${env:package_version}.apk
    upload_script: |
        #!/usr/bin/env bash

        if [[ "$CIRRUS_RELEASE" == "" ]]; then
            echo "Not a release. No need to deploy!"
            exit 0
        fi

        if [[ "$GITHUB_TOKEN" == "" ]]; then
            echo "Please provide GitHub access token via GITHUB_TOKEN environment variable!"
            exit 1
        fi

        file_content_type="application/octet-stream"

        files_to_upload=(
            "/tmp/cirrus-ci-build/bin/Release/net6.0-android/publish/Juka_${env:package_version}.apk"
        )

        for fpath in "${files_to_upload[@]}"
        do
            echo "Uploading $fpath..."
            name=$(basename "$fpath")
            url_to_upload="https://uploads.github.com/repos/$CIRRUS_REPO_FULL_NAME/releases/$CIRRUS_RELEASE/assets?name=$name"
            curl -X POST \
            --data-binary @$fpath \
            --header "Authorization: token $GITHUB_TOKEN" \
            --header "Content-Type: $file_content_type" \
            $url_to_upload
        done